[package]
name = "evm-ffi"
version = "0.11.0"
authors = ["Wei Tang <hi@that.world>", "Mike Lubinets <lubinetsm@yandex.ru>"]
repository = "https://github.com/ethereumproject/evm-ffi"
license-file = "LICENSE"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
ethereum-bigint = { version = "0.2", default-features = false }
evm = { version = "0.11.0", default-features = false }
evm-network = { version = "0.11.0", default-features = false }
evm-network-classic = { version = "0.11.0", default-features = false, optional = true }
smallvec = { version = "0.6.8", default-features = false }
env_logger = { version = "0.5.13", optional = true }
lazy_static = { version = "1.3.0", optional = true }

[features]
default = ["std", "rust-secp256k1", "rlp", "log", "legacy"]
rlp = ["ethereum-bigint/rlp", "evm-network/rlp", "evm-network-classic/rlp" ]
c-secp256k1 = ["evm/c-secp256k1", "evm-network/c-secp256k1", "evm-network-classic/c-secp256k1"]
rust-secp256k1 = ["evm/rust-secp256k1", "evm-network/rust-secp256k1", "evm-network-classic/rust-secp256k1"]
std = ["evm/std", "evm-network/std", "evm-network-classic/std", "smallvec/std"]
log = ["env_logger"]
legacy = ["evm-network-classic", "lazy_static"]
